name: build ipk files
on:
  push:
    tags:
      - '**'
  workflow_dispatch:

jobs:
  build:
    name: ${{ matrix.arch }} build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch:
          - rockchip-armv8-openwrt-22.03

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Build
        uses: openwrt/gh-action-sdk@main
        env:
          ARCH: ${{ matrix.arch }}

      - name: Store packages
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.arch}}-packages
          path: bin/packages/${{ matrix.arch }}/packages/*.ipk

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: "bin/packages/${{ matrix.arch }}/action/*.ipk"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
