name: build ipk files
on:
  push:
    tags:
      - '**'
#  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    name: ${{ matrix.arch }} build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch:
          - aarch64_generic
          - x86_64
          - mips_24kc
          - mipsel_24kc
        branch:
          - openwrt-22.03

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
          path: "shadowproxy"

      - name: Build
        uses: openwrt/gh-action-sdk@main
        env:
          ARCH: ${{ matrix.arch }}-${{ matrix.branch }}
          PACKAGES: "shadowproxy"
          FEED_DIR: ${{ github.workspace }}

      - name: Store packages
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.arch}}-packages
          path: bin/packages/${{ matrix.arch }}/action/*.ipk

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: "bin/packages/${{ matrix.arch }}/action/*.ipk"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
